import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/Navbar'


import airBnbBG from '../public/airBnbBG.jpg'
import photoLocations from '../data/photoLocations.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SHL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <section className={styles.splash}>
          <Image src={airBnbBG} />
          <div className={styles.centerText}>
            <p className={styles.text}>Not sure what to shoot? Perfect.</p>
            <button className={styles.middleSearchButton}>I'm flexible</button>
          </div>
        </section>
        <section className={styles.sectional}>
          <div className={styles.sectionalTitle}>Explore by location</div>
          <div className={styles.sectionalGrid}>
            {
              photoLocations.map(location => {
                return (
                  <div key={location.distance} className={styles.locationCard}>
                    <span>photoPlaceholder</span>
                    <span className={styles.locationCardInfo}>
                      <span className={styles.locationName}>
                        {location.photoLocation}
                      </span>
                      <span>
                        {
                          (parseInt(location.distance) < 60)
                            ? `${location.distance} min drive`
                            : `${location.distance / 60} hour drive`
                        }

                      </span>
                    </span>

                  </div>
                )
              })
            }
          </div>
        </section>
        <section>
          <p className={styles.test}>First</p>
          <p className={styles.test}>Second</p>
        </section>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}