import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Login.module.css'
import { useState } from 'react'
import Navbar from '../components/navbar/Navbar'

import React from 'react'

export default function Login() {
  const [loginUser, setLoginUser] = useState('');
  const [loginPassword, setLoginPassword] = useState('');

  const updateUsername = (e) => {
    const username = e.target.value;
    setLoginUser(username);
  }

  const updatePassword = (e) => {
    const password = e.target.value;
    setLoginPassword(password);
  }

  const validateLogin = (e) => {
    e.preventDefault()
    console.log(loginUser, loginPassword)
  }

  return (
    <div>
      <Head>
        <title>SHL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Login Page
        <form onSubmit={(e) => validateLogin(e)}>
          <input onChange={(e) => updateUsername(e)} placeholder="email or username"></input>
          <input onChange={(e) => updatePassword(e)} type="password" placeholder="password"></input>
          <input type="submit"></input>
        </form>
      </div>
    </div>
  )
}
