import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Login.module.css'
import Navbar from '../components/navbar/Navbar'

import React from 'react'

export default function Login() {
  return (
    <div>
      <Head>
        <title>SHL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Login Page
        <form>
          <input placeholder="email or username"></input>
          <input type="password" placeholder="password"></input>
          <input type="submit"></input>
        </form>
      </div>
    </div>
  )
}
